POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZjhjMDIzYjQ1YjdkYzJjNTc3OTRlZWEiLCJpYXQiOjE2MDMwMTM4Mjl9.Rnus5WKeP_wU-lDxfEzmHSYP-vPaqm5oBrP7SZ_qtpw

{
  "content": "Single page apps use token authentication",
  "important": false
}